Document: webkitsupplemental
Title: Debian webkitsupplemental Manual
Author: <insert document author here>
Abstract: This manual describes what webkitsupplemental is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webkitsupplemental/webkitsupplemental.sgml.gz

Format: postscript
Files: /usr/share/doc/webkitsupplemental/webkitsupplemental.ps.gz

Format: text
Files: /usr/share/doc/webkitsupplemental/webkitsupplemental.text.gz

Format: HTML
Index: /usr/share/doc/webkitsupplemental/html/index.html
Files: /usr/share/doc/webkitsupplemental/html/*.html
